[package]
name = "epoll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vmm-sys-util = '0.12'
libc = "0.2"
log = "0.4"
nix = "0.27"
anyhow = "1.0"
thiserror = "1.0"